apiVersion: v1
kind: Pod
metadata:
  name: inspect-fedora-latest
  labels:
    name: inspect-fedora-latest
spec:
  containers:
  - name: image-inspector
    image: docker.io/openshift/image-inspector:latest
    command:
    - /usr/bin/image-inspector
    - --image=registry.access.redhat.com/rhel7/rhel:latest
    - --path=/var/tmp/image-content
    - --serve=0.0.0.0:8080
    - --scan-type=openscap
    - --chroot
    ports:
    - containerPort: 8080
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
